name: Scrape Lidl and update offers

on:
  workflow_dispatch:       # запуск вручную
  schedule:
    - cron: "0 */6 * * *"  # каждые 6 часов

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers (with deps)
        run: npx playwright install --with-deps

      - name: Run Lidl scraper
        run: npm run scrape:lidl

      - name: Commit and push updated offers.json
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          if git status --porcelain public/data/offers.json | grep -q "public/data/offers.json"; then
            git add public/data/offers.json
            git commit -m "chore: update Lidl offers [skip ci]"
            git push
          else
            echo "No changes in offers.json"
          fi